# Generated by Django 6.0.1 on 2026-04-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='passing_year',
            new_name='experience',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='city',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='linkedin',
            new_name='resume',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='country',
            new_name='role',
        ),
        migrations.RemoveField(
            model_name='application',
            name='course',
        ),
        migrations.AddField(
            model_name='application',
            name='skills',
            field=models.CharField(default='NA', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='work_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='company',
            field=models.CharField(max_length=100),
        ),
    ]
