# Generated by Django 6.0.1 on 2026-04-15 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0002_rename_passing_year_application_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='role',
        ),
    ]
