# Generated by Django 6.0.1 on 2026-05-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0003_remove_application_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
