# Generated by Django 6.0.1 on 2026-04-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_register_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='user',
        ),
        migrations.AlterField(
            model_name='register',
            name='photo',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
