# Generated by Django 6.0.1 on 2026-04-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('logo', models.URLField()),
                ('position', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('posted', models.CharField(max_length=50)),
            ],
        ),
    ]
