# Generated by Django 6.0.1 on 2026-05-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
